#!/bin/bash
#script for creating laravel projects

#function to check if command exists
exists(){
    command -v "$1" >  /dev/null 2>&1
}

if !( exists php); then
 	echo "PHP is not installed."
	echo 'Would you like to install php?(y/n)'
	read ans
	if [ $ans == 'y' -o $ans == 'Y' ]; then 
		sudo apt install php
	else
		echo "Aborting..."
		exit 1
	fi
fi

#checking if composer is installed
if ! (exists composer); then
 	echo "Composer is not installed. Aborting..."
	echo 'Would you like to install Composer?(y/n)'
	read ans
	if [ $ans == 'y' -o $ans == 'Y' ]; then 
		sudo apt install composer
	else
		echo "Aborting..."
		exit 1
	fi
fi

if [ $# -gt 0 ]; then
	composer create-project --prefer-dist laravel/laravel $1;
else
	echo 'Please enter the name of the project';
fi
